<?php
/**
 * Status
 *
 * PHP version 5
 *
 * @category Class
 * @package  HapiPush
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* HAPI Data Model
 *
* HAPI External Data Model
 *
* OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace HapiPush\Model;
use \HapiPush\ObjectSerializer;

/**
 * Status Class Doc Comment
 *
 * @category Class
 * @description current status of reservation
 * @package  HapiPush
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Status
{
    /**
     * Possible values of this enum
     */
    const REQUESTED = 'REQUESTED';
const RESERVED = 'RESERVED';
const IN_HOUSE = 'IN_HOUSE';
const CANCELLED = 'CANCELLED';
const CHECKED_OUT = 'CHECKED_OUT';
const NO_SHOW = 'NO_SHOW';
const WAIT_LIST = 'WAIT_LIST';
const UNKNOWN = 'UNKNOWN';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::REQUESTED,
self::RESERVED,
self::IN_HOUSE,
self::CANCELLED,
self::CHECKED_OUT,
self::NO_SHOW,
self::WAIT_LIST,
self::UNKNOWN,        ];
    }
}
