<?php
/**
 * GuestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HapiPush
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Streaming Flow Webservice
 *
 * - sample API definition for a vendor webservice that receives data from a Hapi Streaming Flow - definition provided as an example only
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace HapiPush;

use PHPUnit\Framework\TestCase;

/**
 * GuestTest Class Doc Comment
 *
 * @category    Class
 * @description profile info for guest(s)
 * @package     HapiPush
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GuestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Guest"
     */
    public function testGuest()
    {
    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {
    }

    /**
     * Test attribute "is_primary"
     */
    public function testPropertyIsPrimary()
    {
    }

    /**
     * Test attribute "arrival_transport"
     */
    public function testPropertyArrivalTransport()
    {
    }

    /**
     * Test attribute "departure_transport"
     */
    public function testPropertyDepartureTransport()
    {
    }
}
