<?php
/**
 * InventoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HapiPush
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* HAPI Data Model
 *
* HAPI External Data Model
 *
* OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace HapiPush;

/**
 * InventoryTest Class Doc Comment
 *
 * @category    Class
 * @description availability by type
 * @package     HapiPush
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Inventory"
     */
    public function testInventory()
    {
    }

    /**
     * Test attribute "inventory_info"
     */
    public function testPropertyInventoryInfo()
    {
    }

    /**
     * Test attribute "inventory_counts"
     */
    public function testPropertyInventoryCounts()
    {
    }
}
